services:

    platform.email.application_mailer:
        class: PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    platform.doctrine_listener.application_creation:
        class: PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
          - "@platform.email.application_mailer"
        tags:
          - { name: doctrine.event_listener, event: postPersist }


    platform.purger.advert:
        class: PlatformBundle\Purger\AdvertPurger
        arguments:
          - "@doctrine.orm.entity_manager"